import type { Machine } from "@/types/machine";

export const machines: Machine[] = [
  {
    id: "1",
    category: "Excavator",
    company: "CAT (Caterpillar)",
    model: "CAT 320",
    image: "/excavator.webp",
    location: "Indore",
    pricePerMonth: 18500,
    availability: "yes",
    ownerName: "XYZ Construction",
    ownerContact: "+91 9980952438",
    description:
      "20-ton crawler excavator, ideal for digging, trenching, and heavy site work. Operator available on request.",
    modelYear: 2020,
    hoursUsed: 5200,
  },
  {
    id: "2",
    category: "Concrete Pump",
    company: "Schwing",
    model: "Schwing 36m Boom",
    image: "/concrete.webp",
    location: "Indore",
    pricePerMonth: 14000,
    availability: "yes",
    ownerName: "BuildRight Equipments",
    ownerContact: "+91 98220 11223",
    description:
      "Boom concrete pump with 36m reach. Suited for multi-storey pours. Diesel powered, well maintained.",
    modelYear: 2022,
    hoursUsed: 1800,
  },
  {
    id: "3",
    category: "Fiori",
    company: "Fiori",
    model: "DB 460",
    image: "/fiori.webp",
    location: "Dewas",
    pricePerMonth: 12000,
    availability: "no",
    availableFrom: "2025-06-12",
    ownerName: "Sharma Infra",
    ownerContact: "+91 99999 88776",
    description:
      "Self-loading concrete mixer, 4.6 m³ drum. Mixes and transports concrete on site. Minimum one-day rental.",
    modelYear: 2019,
    hoursUsed: 6700,
  },
  {
    id: "4",
    category: "JCB",
    company: "JCB",
    model: "JCB 3DX",
    image: "/jcb.webp",
    location: "Indore",
    pricePerMonth: 9500,
    availability: "yes",
    ownerName: "Verma Earthmovers",
    ownerContact: "+91 90011 22334",
    description:
      "Backhoe loader for digging, loading, and light demolition. Versatile all-rounder for any site.",
    modelYear: 2021,
    hoursUsed: 3400,
  },
  {
    id: "5",
    category: "Excavator",
    company: "JCB",
    model: "JCB NXT 140",
    image: "/excavator.webp",
    location: "Ujjain",
    pricePerMonth: 16000,
    availability: "yes",
    ownerName: "Verma Earthmovers",
    ownerContact: "+91 90011 22334",
    description:
      "Reliable mid-size excavator for foundation work and bulk excavation. Fuel-efficient.",
    modelYear: 2023,
    hoursUsed: 900,
  },
  {
    id: "6",
    category: "Concrete Pump",
    company: "Putzmeister",
    model: "Putzmeister Line Pump",
    image: "/concrete.webp",
    location: "Dewas",
    pricePerMonth: 15500,
    availability: "no",
    availableFrom: "2025-06-05",
    ownerName: "BuildRight Equipments",
    ownerContact: "+91 98220 11223",
    description:
      "High-capacity line pump for large commercial pours. Comes with experienced operator.",
    modelYear: 2020,
    hoursUsed: 4500,
  },
];